name: Deploy On Production
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        debug: ${{ secrets.DEBUG }}
        script: |
          cd /home/zeeshan/moviepedia-bot
          /usr/bin/git pull
          sudo /usr/sbin/service moviepedia-bot restart
        